//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectorioPNP2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jefes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jefes()
        {
            this.UnidadPNPs = new HashSet<UnidadPNPs>();
        }
    
        public int idJefe { get; set; }
        public string cip { get; set; }
        public string grado { get; set; }
        public string apPaterno { get; set; }
        public string apMaterno { get; set; }
        public string nombres { get; set; }
        public string celularP { get; set; }
        public System.DateTime dateCreate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public bool isDeleted { get; set; }
        public string userModified { get; set; }
        public string userCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadPNPs> UnidadPNPs { get; set; }
    }
}
