//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectorioPNP2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int idTelefono { get; set; }
        public string numero { get; set; }
        public string tipo { get; set; }
        public string operadora { get; set; }
        public string titular { get; set; }
        public System.DateTime dateCreate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public bool isDeleted { get; set; }
        public string userModified { get; set; }
        public string userCreated { get; set; }
        public Nullable<int> idUnidadPNP { get; set; }
    
        public virtual UnidadPNPs UnidadPNPs { get; set; }
    }
}
