//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectorioPNP2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadPNPs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidadPNPs()
        {
            this.Telefonos = new HashSet<Telefonos>();
        }
    
        public int idUnidadPNP { get; set; }
        public string nombreComun { get; set; }
        public string nombreOficial { get; set; }
        public string correo { get; set; }
        public string calle { get; set; }
        public string distrito { get; set; }
        public string provincia { get; set; }
        public string departamento { get; set; }
        public System.DateTime dateCreate { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public bool isDeleted { get; set; }
        public string userModified { get; set; }
        public string userCreated { get; set; }
        public Nullable<int> idJefe { get; set; }
    
        public virtual Jefes Jefes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefonos> Telefonos { get; set; }
    }
}
